
name: Java CI con Ant

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven Compiler
      run: |
        mkdir -p bin
        mvn dependency:get -Dartifact=javax.servlet:javax.servlet-api:4.0.1 -Ddest=servlet-api.jar
        find src -name "*.java" > sources.txt
        javac -d bin -cp "servlet-api.jar" @sources.txt



